# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rcommand.proto\x12\x0brpi.command"!\n\x0e\x43ommandRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t"E\n\x0f\x43ommandResponse\x12\x12\n\nreturncode\x18\x01 \x01(\x05\x12\x0e\n\x06stdout\x18\x02 \x01(\t\x12\x0e\n\x06stderr\x18\x03 \x01(\t2\xa1\x01\n\x07\x43ommand\x12\x46\n\x07\x45xecute\x12\x1b.rpi.command.CommandRequest\x1a\x1c.rpi.command.CommandResponse"\x00\x12N\n\rExecuteStream\x12\x1b.rpi.command.CommandRequest\x1a\x1c.rpi.command.CommandResponse"\x00\x30\x01\x42!\n\x0brpi.commandB\nRpiCommandP\x01\xa2\x02\x03HLWb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "command_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"\n\013rpi.commandB\nRpiCommandP\001\242\002\003HLW"
    )
    _globals["_COMMANDREQUEST"]._serialized_start = 30
    _globals["_COMMANDREQUEST"]._serialized_end = 63
    _globals["_COMMANDRESPONSE"]._serialized_start = 65
    _globals["_COMMANDRESPONSE"]._serialized_end = 134
    _globals["_COMMAND"]._serialized_start = 137
    _globals["_COMMAND"]._serialized_end = 298
# @@protoc_insertion_point(module_scope)
