"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CommandRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COMMAND_FIELD_NUMBER: builtins.int
    command: builtins.str
    """shell command"""
    def __init__(
        self,
        *,
        command: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["command", b"command"]) -> None: ...

global___CommandRequest = CommandRequest

@typing.final
class CommandResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RETURNCODE_FIELD_NUMBER: builtins.int
    STDOUT_FIELD_NUMBER: builtins.int
    STDERR_FIELD_NUMBER: builtins.int
    returncode: builtins.int
    """shell returncode"""
    stdout: builtins.str
    """标准输出内容"""
    stderr: builtins.str
    """标准错误内容"""
    def __init__(
        self,
        *,
        returncode: builtins.int = ...,
        stdout: builtins.str = ...,
        stderr: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "returncode", b"returncode", "stderr", b"stderr", "stdout", b"stdout"
        ],
    ) -> None: ...

global___CommandResponse = CommandResponse
